name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is affected?
      options:
        - Android
        - iOS
        - Unity
        - Web/Node.js
        - Multiple platforms
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Which version of the GameAlytics SDK are you using?
      placeholder: "e.g., 2.0.0"
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: Platform Version
      description: What version of the platform are you using?
      placeholder: "e.g., Android 12, iOS 16, Unity 2022.3, Node.js 18"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize SDK with '...'
        2. Call method '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces
      description: Please copy and paste any relevant log output or stack traces.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, device info, etc.).
