name: Feature Request
description: Suggest an idea for the Gamepulse SDK
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature target?
      multiple: true
      options:
        - Android
        - iOS
        - Unity
        - Web/Node.js
        - All platforms
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Provide code examples showing how this feature would be used.
      render: javascript

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature is backward compatible

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
