name: Publish SDKs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 2.0.0)'
        required: true
        default: '2.0.0'

jobs:
  publish-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Android SDK (JitPack will auto-publish from releases)
        run: |
          cd packages/android
          ./gradlew build --no-daemon --stacktrace

  publish-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Validate Podspec
        run: |
          cd packages/ios
          pod lib lint GameAlytics.podspec --allow-warnings --skip-import-validation

      - name: Publish to CocoaPods
        run: |
          cd packages/ios
          pod trunk push GameAlytics.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        continue-on-error: true

  publish-unity:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Unity Package to npm
        run: |
          cd packages/unity
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create Unity Package for GitHub Release
        run: |
          cd packages/unity
          npm pack
          
      - name: Upload Unity Package
        uses: actions/upload-artifact@v4
        with:
          name: unity-package
          path: packages/unity/*.tgz

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install root dependencies
        run: npm ci

      - name: Install package dependencies
        run: |
          cd packages/core
          npm ci --ignore-scripts
          cd ../web
          npm ci --ignore-scripts

      - name: Build packages
        run: |
          cd packages/core
          npm run build
          cd ../web
          npm run build

      - name: Publish Core SDK
        run: |
          cd packages/core
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Web SDK
        run: |
          cd packages/web
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: [publish-android, publish-unity, publish-npm]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Create Unity Package
        run: |
          cd packages/unity
          zip -r ../../gamealytics-unity-${{ github.ref_name }}.zip . -x "*.meta" "Library/*" "Temp/*"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: gamealytics-unity-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
